source_list:
  - SB
  - OL
  - CP
  - ADDR


target_list:
  - RTL_TXN_FCT

s3_conf:
  s3_bucket: test-sairam-test
  staging_dir: staging

redshift_conf:
  filetype: csv
  delimiter: |
  dbtable: PUBLIC.TXN_FCT
  query: SELECT txn_id, create_time, amount, cust_id from PUBLIC.TXN_FCT
SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
      database: customers
      collection: address
CP:
  filename: KC_Extract_1_20171009.csv

REGIS_DIM:
  source_data: CP
  loading_query: >
    SELECT
      fn_uuid() AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
      FROM
        CP
      WHERE
        ins_date = CURRENT_DATE
      ) CP
CHILD_DIM:
  source_data: CP
  loading_query: >
    SELECT
      fn_uuid() AS CHILD_KEY, REGIS_CNSM_ID AS CNSM_ID, REGIS_CTY_CODE AS CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_date
    FROM
      (SELECT DISTINCT REGIS_CNSM_ID, REGIS_CTY_CODE, CHILD_ID, CHILD_NB, CHILD_GENDER, ins_date
       FROM
        CP
       WHERE
        ins_date = CURRENT_DATE
        AND CHILD_ID IS NOT NULL
      ) CP

RTL_TXN_FCT:
  loading_query: >
	 select
	   *
	 from
	  """${conf.STAGING_SCHEMA}"""_STG_TRANSACTION_SYNC TXN LEFT OUTER JOIN """${conf.STAGING_SCHEMA}"""_STG_OL_TRANSACTION_SYNC REC
      ON (TXN.APP_TRANSACTION_ID = REC.SB_TRANSACTION_ID )
      LEFT OUTER JOIN """${conf.CUSTOMERS_SCHEMA}"""_REGIS_DIM REG
      ON TXN.LOYALTY_ID = REG.CNS_ID
