source_list:
  - SB
  - OL
  - CP
  - ADDR


target_list:
  - REGIS_DIM

s3_conf:
  s3_bucket: test-sairam-test
  staging_dir: staging

SB:
  mysql_conf:
    dbtable: testdb.TRANSACTIONSYNC
    partition_column: App_Transaction_Id
    query : "(select * from testdb.TRANSACTIONSYNC where Internal_Member_Id = 'PC7135361') as t"

OL:
  sftp_conf:
      filetype: csv
      delimiter: |
      directory: /home/ubuntu/data

ADDR:
  mongodb_config:
      database: customers
      collection: address
CP:
  filename: KC_Extract_1_20171009.csv

REGIS_DIM:
  source_data: CP
  loading_query: >
    SELECT
      fn_uuid AS REGIS_KEY, REGIS_CNSM_ID AS CNSM_ID,REGIS_CTY_CODE AS CTY_CODE,
      REGIS_ID, REGIS_DATE, REGIS_LTY_ID AS LTY_ID, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
    FROM
      (SELECT
        DISTINCT REGIS_CNSM_ID, CAST(REGIS_CTY_CODE AS SMALLINT), CAST(REGIS_ID AS INTEGER),
        REGIS_LTY_ID, REGIS_DATE, REGIS_CHANNEL, REGIS_GENDER, REGIS_CITY, ins_date
      FROM
        CP
      WHERE
        ins_date = CURRENT_DATE
      ) CP

